name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker Compose
      run: docker-compose up -d
    
    - name: Run Tests
      run: |
        # Add your test commands here
        docker-compose exec web python -m pytest
