name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r app/requirements.txt
    
    - name: Build Docker Compose
      run: docker-compose up -d
    
    - name: Run Tests
      run: |
        # Basic health check test
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
        if [ $response -ne 200 ]; then
          echo "Health check failed with status code $response"
          exit 1
        fi
