name: Test Self-Hosted Runner
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "Self-hosted runner is working!"
