name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r app/requirements.txt
    
    - name: Build and Start Docker Compose
      run: |
        docker-compose up -d
        sleep 30  # Wait for services to start
    
    - name: Run Health Check
      run: |
        # Wait for service to be fully ready
        max_attempts=10
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health || true)
          if [ "$response" = "200" ]; then
            echo "Health check passed"
            exit 0
          fi
          echo "Attempt $attempt: Health check failed with status $response"
          sleep 10
          attempt=$((attempt + 1))
        done
        echo "Health check failed after $max_attempts attempts"
        docker-compose logs  # Print logs for debugging
        exit 1
    
    - name: Run Tests
      run: |
        pip install requests
        pytest tests/
    
    - name: Show Logs on Failure
      if: failure()
      run: |
        docker-compose ps
        docker-compose logs
